### ISSUE TITLE
Question about other model

### ISSUE THREAD

**Issue by VietPT3502** [LetheSec/Fer2013-Recognition-Pytorch#9]
Hi, i want to ask if u have try bigger resnet like resnet50? will this help to increase performance or it will only leads to overfitting ?

**Comment by LetheSec** [comment]
I tried several model architectures below, but not including ResNet50. 

(Due to the requirements of the course project, the results in the table below are not trained with the full original data set and, for reference only)

![image](https://github.com/LetheSec/Fer2013-Facial-Emotion-Recognition-Pytorch/assets/40514544/2f41c548-7b30-41aa-9031-169d85704fd5)
